    <h1><?php echo __('FOOTER_CHANGE_PW'); ?></h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
      <fieldset>
        <ol>
          <li>
            <label for="password_old"><?php echo __('CHANGE_PW_CURRENT'); ?></label>
            <?php response::getFormError('password_old'); ?><input type="password" name="password_old" id="password_old" />
          </li>
          <li>
            <label for="password"><?php echo __('CHANGE_PW_NEW'); ?></label>
            <?php response::getFormError('password'); ?><input type="password" name="password" id="password" />
            <span class="description"><?php echo __('CHANGE_PW_NEW_INFO'); ?></span>
          </li>
          <li>
            <label for="password_repeat"><?php echo __('CHANGE_PW_REPEAT'); ?></label>
            <?php response::getFormError('password_repeat'); ?><input type="password" name="password_repeat" id="password_repeat" />
          </li>
          <li><button type="submit" name="save_password" value="yes"><?php echo __('CHANGE_PW_SAVE'); ?></button></li>
        </ol>
      </fieldset>
    </form>
