    <h1>Byt lösenord</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
      <fieldset>
        <ol>
          <li>
            <label for="password_old">Nuvarande lösenord</label>
            <?php response::getFormError('password_old'); ?><input type="password" name="password_old" id="password_old" />
          </li>
          <li>
            <label for="password">Nytt lösenord</label>
            <?php response::getFormError('password'); ?><input type="password" name="password" id="password" />
            <span class="description">Minst 8 tecken.</span>
          </li>
          <li>
            <label for="password_repeat">Repetera nytt lösenord</label>
            <?php response::getFormError('password_repeat'); ?><input type="password" name="password_repeat" id="password_repeat" />
          </li>
          <li><button type="submit" name="save_password" value="yes">Spara lösenord</button></li>
        </ol>
      </fieldset>
    </form>
