<?php loadFallbackLanguage('News'); ?>
      <h2><?php echo __('NEWS_PAGE_HEADER'); ?></h2>

<?php
$id = $controller->id;

$content = $controller->content;
if ($content == '')
  {
  $content = '{"num_news":10,"order":"DESC","html_before":"","html_after":"","html_format":" <h3>%title%</h3><p class=\\"datetime\\">' . __('NEWS_PAGE_WRITTEN_BY') . ' %creator%, %datetime%</p>%content%"}';
  }

$settings = json_decode($content);
?>
      <fieldset>
        <ol>
          <li><label for="num_news_<?php echo $id; ?>"><?php echo __('NEWS_PAGE_COUNT'); ?></label> <input type="text" name="num_news_<?php echo $id; ?>" id="num_news_<?php echo $id; ?>"<?php Request::formStatePost('num_news_' . $id, 'text', '', $settings->num_news); ?> /></li>
          <li><label for="order_asc_<?php echo $id; ?>"><?php echo __('NEWS_PAGE_SORT_ASC'); ?></label> <input type="radio" name="order_<?php echo $id; ?>" id="order_asc_<?php echo $id; ?>" value="ASC"<?php Request::formStatePost('order_' . $id, 'radio', 'ASC', $settings->order); ?> />
            <label for="order_desc_<?php echo $id; ?>"><?php echo __('NEWS_PAGE_SORT_DESC'); ?></label> <input type="radio" name="order_<?php echo $id; ?>" id="order_desc_<?php echo $id; ?>" value="DESC"<?php Request::formStatePost('order_' . $id, 'radio', 'DESC', $settings->order); ?> /></li>
          <li><label for="html_before_<?php echo $id; ?>"><?php echo __('NEWS_PAGE_HTML_BEFORE'); ?></label> <input type="text" name="html_before_<?php echo $id; ?>" id="html_before_<?php echo $id; ?>"<?php Request::formStatePost('html_before_' . $id, 'text', '', $settings->html_before); ?> /></li>
          <li><label for="html_after_<?php echo $id; ?>"><?php echo __('NEWS_PAGE_HTML_AFTER'); ?></label> <input type="text" name="html_after_<?php echo $id; ?>" id="html_after_<?php echo $id; ?>"<?php Request::formStatePost('html_after_' . $id, 'text', '', $settings->html_after); ?> /></li>
          <li><label for="html_format_<?php echo $id; ?>"><?php echo __('NEWS_PAGE_HTML_NEWS'); ?></label> <textarea name="html_format_<?php echo $id; ?>" id="html_format_<?php echo $id; ?>" cols="50" rows="3"><?php Request::formStatePost('html_format_' . $id, 'textarea', '', $settings->html_format); ?></textarea></li>
        </ol>
      </fieldset>
