<?php loadFallbackLangugage('Calendar'); ?>
      <h2><?php echo __('CALENDAR_FAV_NEW_HEADER'); ?></h2>

      <form action="<?php echo urlModr('calendar'); ?>" method="post">
        <fieldset>
          <ol>
            <li><label for="title"><?php echo __('CALENDAR_TITLE'); ?></label> <input type="text" name="title" id="title" maxlength="30"<?php Request::formStatePost('title', 'text'); ?> /></li>
            <li><label for="event_content"><?php echo __('CALENDAR_CONTENT'); ?></label> <textarea name="content" id="event_content" cols="80" rows="10"><?php Request::formStatePost('content', 'textarea'); ?></textarea></li>
            <li><label for="starttime"><?php echo __('CALENDAR_STARTDATE_TIME'); ?></label> <input type="text" name="starttime" id="starttime" maxlength="16"<?php Request::formStatePost('starttime', 'text'); ?> />
              <span class="description"><?php echo __('CALENDAR_TIME_FORMAT'); ?></span></li>
            <li><label for="endtime"><?php echo __('CALENDAR_ENDDATE_TIME'); ?></label> <input type="text" name="endtime" id="endtime" maxlength="16"<?php Request::formStatePost('endtime', 'text'); ?> />
              <span class="description"><?php echo __('CALENDAR_TIME_FORMAT'); ?></span></li>
            <li><button type="submit" name="new_event" value="yes"><?php echo __('SAVE'); ?></button></li>
          </ol>
        </fieldset>
      </form>
