      <h2>Kalendermodul</h2>

<?php
$id = $controller->id;

if ($controller->content == '')
  $controller->content = '{"num_events":0,"html_before":"","html_after":"","html_format":" <h3>%title%</h3><p class=\\"datetime\\">%starttime% - %endtime%</p><p>%content%</p>"}';
$settings = json_decode($controller->content);
?>
      <fieldset>
        <ol>
          <li><label for="num_events_<?php echo $id; ?>">Visa antal händelser</label> <input type="text" name="num_events_<?php echo $id; ?>" id="num_events_<?php echo $id; ?>"<?php Request::formStatePost('num_events_' . $id, 'text', '', $settings->num_events); ?> /></li>
          <li><label for="html_before_<?php echo $id; ?>">HTML före</label> <input type="text" name="html_before_<?php echo $id; ?>" id="html_before_<?php echo $id; ?>"<?php Request::formStatePost('html_before_' . $id, 'text', '', $settings->html_before); ?> /></li>
          <li><label for="html_after_<?php echo $id; ?>">HTML efter</label> <input type="text" name="html_after_<?php echo $id; ?>" id="html_after_<?php echo $id; ?>"<?php Request::formStatePost('html_after_' . $id, 'text', '', $settings->html_after); ?> /></li>
          <li><label for="html_format_<?php echo $id; ?>">HTML för händelsen</label> <textarea name="html_format_<?php echo $id; ?>" id="html_format_<?php echo $id; ?>" cols="50" rows="3"><?php Request::formStatePost('html_format_' . $id, 'textarea', '', $settings->html_format); ?></textarea></li>
        </ol>
      </fieldset>
