    <h1><?php echo __('NEWS_DELETE_HEADER'); ?></h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form content-on-close">
      <p><?php echo __('NEWS_QUESTION', '<strong>' . htmlspecialchars($news->title) . '</strong>'); ?></p>

      <p><button type="submit" name="delete_news_yes" value="yes"><?php echo __('YES'); ?></button>
        <button type="submit" name="delete_news_no" value="no" class="hide-boxing"><?php echo __('NO'); ?></button></p>
    </form>
