    <h1>Ta bort mapp</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form content-on-close also-success">
      <p>Är du säker på att du vill ta bort mappen <strong><?php echo htmlspecialchars($path); ?></strong> 
      permanent?</p>

      <p><button type="submit" name="delete_folder_yes" value="yes">Ja</button>
        <button type="submit" name="delete_folder_no" value="no" class="hide-boxing">Nej</button></p>
    </form>
