    <h1>Ta bort sida</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form content-on-close">
      <p>Är du säker på att du vill ta bort sidan <strong><?php echo htmlspecialchars($page->title); ?></strong> 
        samt dess undersidor permanent?</p>

      <p><button type="submit" name="delete_page_yes" value="yes">Ja</button>
        <button type="submit" name="delete_page_no" value="no" class="hide-boxing">Nej</button></p>
    </form>
