    <h1>Ta bort nyhet</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form delete-dialog">
      <p>Är du säker på att du vill ta bort nyheten <strong><?php echo htmlspecialchars($news->title); ?></strong> 
      permanent?</p>

      <p><button type="submit" name="delete_news_yes" value="yes">Ja</button>
        <button type="submit" name="delete_news_no" value="no" class="hide-boxing">Nej</button></p>
    </form>
