    <h1><?php echo __('DELETE_PAGEMOD_HEADER'); ?></h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form content-on-close">
      <p><?php echo __('DELETE_PAGEMOD_QUESTION', '<strong>' . htmlspecialchars($controller->name) . '</strong>', '<strong>' . htmlspecialchars($active_page->title) . '</strong>'); ?></p>

      <p><button type="submit" name="delete_pcontroller_yes" value="yes"><?php echo __('YES'); ?></button>
        <button type="submit" name="delete_pcontroller_no" value="no" class="hide-boxing"><?php echo __('NO'); ?></button>
        <input type="hidden" name="controller_id" value="<?php echo $controller->id; ?>" /></p>
    </form>
