    <h1>Ta bort fil</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form content-on-close">
      <p>Är du säker på att du vill ta bort filen <strong><?php echo htmlspecialchars($path); ?></strong> 
      permanent?</p>

      <p><button type="submit" name="delete_file_yes" value="yes">Ja</button>
        <button type="submit" name="delete_file_no" value="no" class="hide-boxing">Nej</button></p>
    </form>
