    <h1>Redigera nyhet</h1>

    <p><a href="<?php echo urlModr($route); ?>" class="clink">Gå till nyhetslistan</a></p>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
      <fieldset>
        <ol>
          <li><label for="title">Titel</label> <input type="text" name="title" id="title" maxlength="30"<?php Request::formStatePost('title', 'text', '', $news->title); ?> /></li>
          <li><button type="submit" name="edit_news" class="save-domiwyg" value="yes">Spara ändringar</button></li>
        </ol>
      </fieldset>

      <p id="news_content_container">
        <textarea name="content" id="news_content" class="use-domiwyg" cols="100" rows="10"><?php Request::formStatePost('content', 'textarea', '', $news->content); ?></textarea>
      </p>
    </form>
