    <h1><?php echo __('HEADER_USERS'); ?></h1>

    <section class="half-section box">
      <h1><?php echo __('EDIT_USER_HEADER'); ?></h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
        <fieldset>
          <ol>
            <li><label for="name"><?php echo __('USERS_NAME'); ?></label> <input type="text" name="name" id="name" maxlength="50"<?php Request::formStatePost('name', 'text', '', $user->name); ?> /></li>
            <li><label for="rank"><?php echo __('USERS_RANK'); ?></label> <select name="rank" id="rank">
                <option value="1"<?php Request::formStatePost('rank', 'select', 1, $user->rank); ?>><?php echo __('USERRANK_1'); ?></option>
                <option value="2"<?php Request::formStatePost('rank', 'select', 2, $user->rank); ?>><?php echo __('USERRANK_2'); ?></option>
              </select></li>
            <li><button type="submit" name="edit_user" value="yes"><?php echo __('EDIT_USER_SAVE'); ?></button></li>
          </ol>
        </fieldset>
      </form>
    </section>

    <section class="half-section box">
      <h1><?php echo __('EDIT_USER_PW_HEADER'); ?></h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
        <fieldset>
          <ol>
            <li><label for="password"><?php echo __('CHANGE_PW_NEW'); ?></label> <input type="password" name="password" id="password" />
              <span class="description"><?php echo __('EDIT_USER_PW_INFO'); ?></span></li>
            <li><label for="password_repeat"><?php echo __('CHANGE_PW_REPEAT'); ?></label> <input type="password" name="password_repeat" id="password_repeat" /></li>
            <li><button type="submit" name="edit_user_password" value="yes"><?php echo __('CHANGE_PW_SAVE'); ?></button></li>
          </ol>
        </fieldset>
      </form>
    </section>
