<?php $self_url = urlModr($route, $params); ?>
    <h1>Redigera sida</h1>

    <form action="<?php echo $self_url; ?>" method="post" class="ajax-form no-content">
      <fieldset class="collapsable<?php if (!$edit_page) echo ' start-collapsed'; ?>">
        <h2>Sidegenskaper</h2>
        <ol>
          <li><label for="title">Titel</label> <input type="text" name="title" id="title" maxlength="30"<?php request::formStatePost('title', 'text', '', $active_page->title); ?> /></li>
          <li><label for="public">Publicerad?</label> <input type="checkbox" name="public" id="public" value="1"<?php request::formStatePost('public', 'checkbox', 1, $active_page->public); ?> /></li>
          <li><label for="show_in_menu">Synlig i menyn?</label> <input type="checkbox" name="show_in_menu" id="show_in_menu" value="1"<?php request::formStatePost('show_in_menu', 'checkbox', 1, $active_page->show_in_menu); ?> /></li>
          <li><button type="submit" name="edit_page" value="yes">Spara ändringar</button></li>
        </ol>
      </fieldset>
    </form>

    <form action="<?php echo $self_url; ?>" method="post" class="ajax-form">
      <fieldset class="collapsable<?php if (!$add_controller) echo ' start-collapsed'; ?>">
        <h2>Lägg till modul på sidan</h2>
        <ol>
          <li><label for="controller">Modul</label> <select name="controller" id="controller">
<?php foreach ($installed_controllers as $controller): ?>
              <option value="<?php echo $controller->id; ?>"><?php echo $controller->name; ?></option>
<?php endforeach; ?>
            </select></li>
          <li><button type="submit" name="add_controller" value="yes">Lägg till modul</button></li>
        </ol>
      </fieldset>
    </form>

<?php
$max_controllers = count($controllers) - 1;
$i = 0;
foreach ($controllers as $controller): ?>
    <form action="<?php echo $self_url; ?>" method="post">
<?php require(BASE . 'view/admin/controller.page.' . $controller->class_name . '.phtml'); ?>
      <p class="controller-actions">
        <input type="hidden" name="controller_id" value="<?php echo $controller->id; ?>" />
        <button type="submit" name="save_controller" class="save-domiwyg" value="yes">Spara modul</button>
        <button type="submit" name="delete_controller" value="yes" class="delete-controller">Ta bort modul</button>
        <?php if ($i > 0): ?><button type="submit" name="controller_order_up" value="yes">Upp i ordningen</button>
        <?php endif; if ($i < $max_controllers): ?><button type="submit" name="controller_order_down" value="yes">Ner i ordningen</button><?php endif; ?>
      </p>
    </form>

<?php ++$i; endforeach; ?>