    <h1>Användare</h1>

    <section class="half-section box">
      <h1>Redigera användare</h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post">
        <fieldset>
          <ol>
            <li><label for="name">Namn</label> <input type="text" name="name" id="name" maxlength="50"<?php request::formStatePost('name', 'text', '', $user->name); ?> /></li>
            <li><label for="rank">Användarrang</label> <select name="rank" id="rank">
                <option value="1"<?php request::formStatePost('rank', 'select', 1, $user->rank); ?>>Administratör</option>
                <option value="2"<?php request::formStatePost('rank', 'select', 2, $user->rank); ?>>Skribent</option>
              </select></li>
            <li><button type="submit" name="edit_user" value="yes">Spara ändringar</button></li>
          </ol>
        </fieldset>
      </form>
    </section>

    <section class="half-section box">
      <h1>Sätt nytt lösenord</h1>

      <form action="" method="post">
        <fieldset>
          <ol>
            <li><label for="password">Nytt lösenord</label> <input type="password" name="password" id="password" />
              <span class="description">Minst 6 tecken. Lämna tomt för att systemet ska slumpa lösenord åt dig.</span></li>
            <li><label for="password_repeat">Repetera nytt lösenord</label> <input type="password" name="password_repeat" id="password_repeat" /></li>
            <li><button type="submit" name="edit_user_password" value="yes">Spara lösenord</button></li>
          </ol>
        </fieldset>
      </form>
    </section>
