    <h1><?php echo _('HEADER_DASHBOARD'); ?></h1>

    <section class="half-section list">
      <h1><a href="<?php echo urlModr('page'); ?>"><?php echo _('DASHBOARD_PAGES_HEADER'); ?></a></h1>

      <p><?php echo _('DASHBOARD_LAST_EDITS'); ?>:</p>

      <ul class="shortcuts">
<?php foreach ($last_pages as $page): ?>
        <li>
          <a href="<?php echo urlModrSite($page->url); ?>"><?php echo htmlspecialchars($page->title); ?></a> 
          (<?php echo easyDate('H:i', $page->edited) . ' ' . _('DASHBOARD_EDIT_BY') . ' ' . htmlspecialchars($page->name); ?>) 
          <a href="<?php echo urlModr('edit-page', 'show', $page->url); ?>" class="clink edit-link"><?php echo _('ACTION_EDIT'); ?></a>
        </li>
<?php endforeach; ?>
      </ul>
    </section>

    <section class="half-section list">
      <h1><a href="<?php echo urlModr('controllers'); ?>" class="clink"><?php echo _('HEADER_MODULES'); ?></a></h1>
<?php if (count($controllers)): ?>
      <p><?php echo _('DASHBOARD_FAVORITE_MODULES'); ?>:</p>

      <ul class="shortcuts">
<?php foreach ($controllers as $controller): ?>
        <li><a href="<?php echo urlModr($controller->class_name); ?>" class="clink"><?php echo htmlspecialchars($controller->name); ?></a></li>
<?php endforeach; ?>
      </ul>
<?php endif; ?>
    </section>

<?php foreach ($controllers as $controller):
   if ($controller->has_favorite_config): ?>
    <section class="half-section">
<?php require('controller.favorite.' . $controller->class_name . '.phtml'); ?>
    </section>

<?php endif;
endforeach; ?>
