<?php
$page = (isset($this->request) ? $this->request->params[0] : '');
$data['stylesheets'] = array_unique($data['stylesheets']);
$data['scripts'] = array_unique($data['scripts']);

function menuLink($current_page, $new_page)
  {
  return '<a href="' . urlModr($new_page) . '" class="menu-item' . ($current_page == $new_page ? ' active' : '') . '">';
  }
?>
<!DOCTYPE html>
<html lang="sv">

<head>
  <title>KWE Admin :: <?php echo $this->title; ?></title>
  <meta charset="utf-8" />
  <link title="KWE Admin" href="<?php echo FULLPATH; ?>/css/kwe_admin<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" media="screen" />
  <link href="<?php echo FULLPATH_SITE; ?>/js/domiwyg.min.css" rel="stylesheet" />
  <link href="<?php echo FULLPATH_SITE; ?>/css/site_domiwyg.css" rel="stylesheet" />
  <link href="<?php echo FULLPATH; ?>/css/kwe_admin_print<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" media="print" />
<?php foreach ($data['stylesheets'] as $stylesheet): ?>
  <link href="<?php echo $stylesheet; ?>" rel="stylesheet" />
<?php endforeach; ?>
  <!--[if lte IE 8]><link href="<?php echo FULLPATH; ?>/css/kwe_admin_ie<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" />
  <script src="<?php echo FULLPATH_SITE; ?>/js/html5.min.js" type="text/javascript"></script><![endif]-->
  <script src="<?php echo FULLPATH_SITE; ?>/js/domiwyg.min.js"></script>
  <script src="<?php echo FULLPATH_SITE; ?>/js/domiwyg.swedish.min.js"></script>
<?php if (MINIFIED): ?>
  <script src="<?php echo FULLPATH_SITE; ?>/js/kwe.min.js"></script>
<?php else: ?>
  <script src="<?php echo FULLPATH_SITE; ?>/js/kwf.js"></script>
  <script src="<?php echo FULLPATH_SITE; ?>/js/kwe.js"></script>
<?php endif; ?>
<?php foreach ($data['scripts'] as $script): ?>
  <script src="<?php echo $script; ?>"></script>
<?php endforeach; ?>
  <script>Kwf.FULLPATH = '<?php echo FULLPATH; ?>'; Kwf.FULLPATH_SITE = '<?php echo FULLPATH_SITE; ?>';
    Kwf.MODR = '<?php echo urlModr(); ?>'; Kwf.MODR_SITE = '<?php echo urlModrSite(); ?>';</script>
</head>

<body id="kwe_<?php if (isset($data['body_id'])) echo $data['body_id']; else echo 'default'; ?>">

<header id="header">
  <div id="header_inner">
    <h1><a href="<?php echo urlModr(); ?>" id="kwe_logo">KWE</a></h1>

    <nav id="navigation">
      <a href="<?php echo FULLPATH_SITE; ?>/" id="goto_firstpage" title="Till din förstasida">Till din förstasida</a>

      <ul>
<?php if (Access::$is_logged_in): ?>
        <li><?php echo menuLink($page, 'index'); ?>Översikt</a></li>
        <li><?php echo menuLink($page, 'page'); ?>Sidor</a></li>
        <li class="submenu-link"><?php echo menuLink($page, 'controllers'); ?>Moduler</a>
<?php
$controllers = $this->request->session->get('controllers');
if ($controllers): ?>
          <ul class="submenu">
<?php foreach ($controllers as $controller): ?>
            <li><a href="<?php echo urlModr($controller[1]); ?>" class="submenu-item"><?php echo $controller[0]; ?></a></li>
<?php endforeach; ?>
          </ul><?php endif; ?></li>
<?php if (Access::$user->rank == 1): ?>
        <li><?php echo menuLink($page, 'settings'); ?>Inställningar</a></li>
        <li><?php echo menuLink($page, 'users'); ?>Användare</a></li>
<?php endif; ?>
        <li><?php echo menuLink($page, 'logout'); ?>Logga ut</a></li>
<?php else: ?>
        <li><?php echo menuLink($page, 'index'); ?>Logga in</a></li>
<?php endif; ?>
      </ul>
    </nav>
  </div>
</header>

<div id="page">
<?php if (count($this->error_messages)): ?>
  <ul id="errorlist">
<?php foreach ($this->error_messages as $msg): ?>
    <li><?php echo $msg; ?></li>
<?php endforeach; ?>
  </ul>
<?php endif; 

if (count($this->info_messages)): ?>
  <ul id="infolist">
<?php foreach ($this->info_messages as $msg): ?>
    <li><?php echo $msg; ?></li>
<?php endforeach; ?>
  </ul>
<?php endif; ?>

  <div id="content">

<?php echo $this->content_data; ?>

  </div>

  <footer id="footer">
    <p id="version"><?php echo KWE_VERSION; ?></p>
    <p id="copyright">Copyright &copy; <a href="http://kekos.se/">Christoffer Lindahl</a>, 2009-2012</p>
    <p id="user-info"><?php if (Access::$is_logged_in): ?>Inloggad som <?php echo Access::$user->name; ?> <a href="<?php echo urlModr('change-password'); ?>" class="blink dim500x300">(Byt lösenord)</a><?php endif; ?></p>
  </footer>
</div>

</body>

</html>