    <h1>Moduler</h1>

<?php if (Access::$user->rank == 1): ?>
    <section class="half-section box">
      <h1>Installera modul</h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post" enctype="multipart/form-data">
        <fieldset>
          <ol>
            <li><label for="file">Installationsfil</label> <input type="file" name="file" id="file" />
              <span class="description">En installationsfil ska ha filändelsen .kwe</span></li>
            <li><button type="submit" name="install_controller" value="yes">Installera</button></li>
          </ol>
        </fieldset>
      </form>
    </section>
<?php endif; ?>

    <section class="half-section box">
      <h1>Modullista</h1>

      <table>
        <tr>
          <th>Namn</th>
          <th class="actions-head">&nbsp;</th>
        </tr>
<?php foreach ($controllers as $controller): ?>
        <tr>
<?php if ($controller->configurable): ?>
          <td><a href="<?php echo urlModr($controller->class_name); ?>" class="clink"><?php echo htmlspecialchars($controller->name); ?></a></td>
<?php else: ?>
          <td><?php echo htmlspecialchars($controller->name); ?></td>
<?php endif; ?>
          <td class="actions"><?php if (Access::$user->rank == 1): ?><a href="<?php echo urlModr('controllers', 'uninstall', $controller->class_name); ?>" class="delete-link">Avinstallera</a><?php
endif;
$favorite_descr = ($controller->favorite ? 'Inte favorit' : 'Favorit');
if ($controller->configurable): ?>
<a href="<?php echo urlModr('controllers', 'favorite', $controller->class_name); ?>" class="<?php if (!$controller->favorite) echo 'not-'; ?>favorite-link clink" title="<?php echo $favorite_descr; ?>"><?php echo $favorite_descr; ?></a><?php endif; ?></td>
        </tr>
<?php endforeach; ?>
      </table>
    </section>
