    <h1>Användare</h1>

    <section class="half-section box">
      <h1>Lägg till användare</h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post">
        <fieldset>
          <ol>
            <li><label for="name">Namn</label> <input type="text" name="name" id="name" maxlength="50"<?php request::formStatePost('name', 'text'); ?> /></li>
            <li><label for="username">Användarnamn</label> <input type="text" name="username" id="username" maxlength="20"<?php request::formStatePost('username', 'text'); ?> /></li>
            <li><label for="password">Lösenord</label> <input type="password" name="password" id="password" />
              <span class="description">Lämna tomt för att slumpa ett lösenord.</span></li>
            <li><label for="rank">Rang</label> <select name="rank" id="rank">
                <option value="1"<?php request::formStatePost('rank', 'select', '', 1); ?>>Administratör</option>
                <option value="2"<?php request::formStatePost('rank', 'select', '', 2); ?>>Skribent</option>
              </select></li>
            <li><button type="submit" name="new_user" value="yes">Spara</button></li>
          </ol>
        </fieldset>
      </form>
    </section>

    <section class="half-section box">
      <h1>Användarlista</h1>

      <table>
        <tr>
          <th>Namn</th>
          <th>Användarnamn</th>
          <th>Senast inloggad</th>
          <th class="actions-head">&nbsp;</th>
        </tr>
<?php foreach ($users as $user): ?>
        <tr>
          <td><?php echo htmlspecialchars($user->name); ?></td>
          <td><a href="<?php echo urlModr('users', 'edit', $user->id); ?>" class="edit-link"><?php echo htmlspecialchars($user->username); ?></a></td>
          <td><?php echo easyDate('H:i', $user->online_time); ?></td>
          <td class="actions"><?php if ($user->rank > 1): ?><a href="<?php echo urlModr('users', 'permissions', $user->id); ?>" class="permission-link">Rättigheter</a><?php endif; ?>
            <a href="<?php echo urlModr('users', 'delete', $user->id); ?>" class="delete-link">Ta bort</a></td>
        </tr>
<?php endforeach; ?>
      </table>
    </section>
