    <h1><?php echo __('HEADER_PAGES'); ?></h1>

    <p class="help-text"><?php echo __('PAGES_HELP'); ?></p>

<?php if (Access::$user->rank == 1 || ($active_page && ($active_page->permission & PERMISSION_ADD))): ?>
    <p><a href="<?php echo urlModr($route, 'addnew', ($active_page ? $active_page->url : '')); ?>" class="clink"><?php echo __('PAGES_NEW_' . ($active_page ? 'SUB' : '') . 'PAGE'); ?></a></p>
<?php endif; ?>

    <table>
      <tr>
        <th><?php echo __('PAGES_TITLE'); ?></th>
        <th><?php echo __('PAGES_URL'); ?></th>
        <th><?php echo __('PAGES_PUBLISHED'); ?></th>
        <th><?php echo __('PAGES_VISIBLE'); ?></th>
        <th><?php echo __('PAGES_LAST_EDIT'); ?></th>
        <th class="actions-head">&nbsp;</th>
      </tr>
<?php if ($active_page): ?>
      <tr>
        <td colspan="6"><a href="<?php echo urlModr('page'); ?>" class="less-link clink"><?php echo __('PAGES_SHOW_ALL_PAGES'); ?></a></td>
      </tr>
<?php endif;
$max_pages = count($pages) - 1;
$i = 0;
foreach ($pages as $page): ?>
      <tr>
        <td<?php if ($active_page && $i > 0) echo ' class="subpage-row"'; ?>><?php if (!$active_page): ?><a href="<?php echo urlModr('page', 'list', $page->url); ?>" class="more-link clink"><?php echo __('PAGES_SHOW_ALL_SUBPAGES'); ?></a>
          <?php endif; ?><a href="<?php echo urlModr('edit-page', 'show', $page->url); ?>" class="clink edit-link"><?php echo htmlspecialchars($page->title); ?></a></td>
        <td><a href="<?php echo urlModrSite($page->url); ?>"><?php echo htmlspecialchars($page->url); ?></a></td>
        <td><?php echo ($page->public ? __('YES') : __('NO')); ?></td>
        <td><?php echo ($page->show_in_menu ? __('YES') : __('NO')); ?></td>
        <td><?php echo easyDate('', $page->edited); ?></td>
        <td class="actions"><a href="<?php echo urlModr('page', 'delete', $page->url); ?>" class="delete-link"><?php echo __('ACTION_DELETE'); ?></a>
<?php if (($active_page && $i > 0) || !$active_page): ?>
          <?php if (($active_page && $i > 1) || (!$active_page && $i > 0)): ?><a href="<?php echo urlModr('page', 'up', $page->url); ?>" class="icon-up clink"><?php echo __('ACTION_UP'); ?></a>
          <?php endif; if ($i < $max_pages): ?><a href="<?php echo urlModr('page', 'down', $page->url); ?>" class="icon-down clink"><?php echo __('ACTION_DOWN'); ?></a><?php endif; ?></td>
<?php endif; ?>
      </tr>
<?php ++$i; endforeach; ?>
    </table>
