    <h1>Kalender</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post">
      <fieldset class="collapsable<?php if (!$new_event) echo ' start-collapsed'; ?>">
        <h2>Ny händelse</h2>
        <ol>
          <li><label for="title">Titel</label> <input type="text" name="title" id="title" maxlength="30"<?php request::formStatePost('title', 'text'); ?> /></li>
          <li><label for="event_content">Innehåll</label> <textarea name="content" id="event_content" cols="80" rows="10"><?php request::formStatePost('content', 'textarea'); ?></textarea></li>
          <li><label for="starttime">Startdatum &amp; -tid</label> <input type="text" name="starttime" id="starttime" maxlength="16"<?php request::formStatePost('starttime', 'text'); ?> />
            <span class="description">Anges i formatet ÅÅÅÅ-MM-DD TT:MM</span></li>
          <li><label for="endtime">Slutdatum &amp; -tid</label> <input type="text" name="endtime" id="endtime" maxlength="16"<?php request::formStatePost('endtime', 'text'); ?> />
            <span class="description">Anges i formatet ÅÅÅÅ-MM-DD TT:MM</span></li>
          <li><button type="submit" name="new_event" value="yes">Spara</button></li>
        </ol>
      </fieldset>
    </form>

    <section class="collapsable">
      <h2>Händelselista</h2>

      <table>
        <tr>
          <th>Titel</th>
          <th>Startdatum</th>
          <th>Slutdatum</th>
          <th class="actions-head">&nbsp;</th>
        </tr>
<?php foreach ($events as $event): ?>
        <tr>
          <td><?php echo htmlspecialchars($event->title); ?></td>
          <td><?php echo easyDate('H:i', $event->starttime); ?></td>
          <td><?php echo easyDate('H:i', $event->endtime); ?></td>
          <td class="actions"><a href="<?php echo urlModr($route, 'edit', $event->id); ?>" class="edit-link">Redigera</a>
            <a href="<?php echo urlModr($route, 'delete', $event->id); ?>" class="delete-link">Ta bort</a></td>
        </tr>
<?php endforeach; ?>
      </table>
    </section>
