    <h1><?php echo __('MODULE_DEFAULT_CALENDAR'); ?></h1>

    <section class="half-section box">
      <h1><?php echo __('CALENDAR_NEW_HEADER'); ?></h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
        <fieldset>
          <ol>
            <li><label for="title"><?php echo __('CALENDAR_TITLE'); ?></label> <input type="text" name="title" id="title" maxlength="30"<?php Request::formStatePost('title', 'text'); ?> /></li>
            <li><label for="event_content"><?php echo __('CALENDAR_CONTENT'); ?></label> <textarea name="content" id="event_content" cols="80" rows="10"><?php Request::formStatePost('content', 'textarea'); ?></textarea></li>
            <li><label for="starttime"><?php echo __('CALENDAR_STARTDATE_TIME'); ?></label> <input type="text" name="starttime" id="starttime" maxlength="16"<?php Request::formStatePost('starttime', 'text'); ?> />
              <span class="description"><?php echo __('CALENDAR_TIME_FORMAT'); ?></span></li>
            <li><label for="endtime"><?php echo __('CALENDAR_ENDDATE_TIME'); ?></label> <input type="text" name="endtime" id="endtime" maxlength="16"<?php Request::formStatePost('endtime', 'text'); ?> />
              <span class="description"><?php echo __('CALENDAR_TIME_FORMAT'); ?></span></li>
            <li><button type="submit" name="new_event" value="yes"><?php echo __('SAVE'); ?></button></li>
          </ol>
        </fieldset>
      </form>
    </section>

    <section class="half-section box">
      <h1><?php echo __('CALENDAR_LIST_HEADER'); ?></h1>

      <table>
        <tr>
          <th><?php echo __('CALENDAR_TITLE'); ?></th>
          <th><?php echo __('CALENDAR_STARTDATE'); ?></th>
          <th><?php echo __('CALENDAR_ENDDATE'); ?></th>
          <th class="actions-head">&nbsp;</th>
        </tr>
<?php foreach ($events as $event): ?>
        <tr>
          <td><a href="<?php echo urlModr($route, 'edit', $event->id); ?>" class="clink edit-link"><?php echo htmlspecialchars($event->title); ?></a></td>
          <td><?php echo easyDate('H:i', $event->starttime); ?></td>
          <td><?php echo easyDate('H:i', $event->endtime); ?></td>
          <td class="actions"><a href="<?php echo urlModr($route, 'delete', $event->id); ?>" class="delete-link"><?php echo __('ACTION_DELETE'); ?></a></td>
        </tr>
<?php endforeach; ?>
      </table>
    </section>
