    <h1>Nyheter</h1>

    <section class="half-section box">
      <h1>Ny nyhet</h1>

      <form action="<?php echo urlModr($route, $params); ?>" method="post">
        <fieldset>
          <ol>
            <li><label for="title">Titel</label> <input type="text" name="title" id="title" maxlength="30"<?php Request::formStatePost('title', 'text'); ?> /></li>
            <li><button type="submit" name="new_news" value="yes">Spara</button></li>
          </ol>
        </fieldset>
      </form>
    </section>

    <section class="half-section box">
      <h1>Nyhetslista</h1>

      <table>
        <tr>
          <th>Titel</th>
          <th>Skapad</th>
          <th class="actions-head">&nbsp;</th>
        </tr>
<?php foreach ($news as $news_item): ?>
        <tr>
          <td><?php echo htmlspecialchars($news_item->title); ?></td>
          <td><?php echo easyDate('H:i', $news_item->created); ?></td>
          <td class="actions"><a href="<?php echo urlModr($route, 'edit', $news_item->id); ?>" class="edit-link">Redigera</a>
            <a href="<?php echo urlModr($route, 'delete', $news_item->id); ?>" class="delete-link">Ta bort</a></td>
        </tr>
<?php endforeach; ?>
      </table>
    </section>
