    <form action="<?php echo urlModr($route, $params); ?>" method="post" id="login_form">
      <fieldset>
        <a href="<?php echo urlModr(); ?>" id="login_logo">KWE</a>

        <h1><?php echo __('HEADER_LOGIN'); ?></h1>

        <ol>
          <li><label for="username"><?php echo __('LOGIN_USERNAME'); ?></label> <input type="text" name="username" id="username" maxlength="20" /></li>
          <li><label for="password"><?php echo __('LOGIN_PASSWORD'); ?></label> <input type="password" name="password" id="password" /></li>
          <li><button type="submit" name="login_submit" value="ok"><?php echo __('LOGIN_SEND'); ?></button></li>
        </ol>
      </fieldset>
    </form>
