    <h1>Ny mapp</h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form content-on-close">
      <p>
        <label for="folder_name">Skapa ny mapp med namnet</label>
        <input type="text" name="folder_name" id="folder_name" />
      </p>
      <p class="clear">
        <button type="submit" name="new_folder" value="yes">Spara</button>
      </p>
    </form>
