    <h1><?php echo __('HEADER_SETTINGS'); ?></h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
      <fieldset>
        <ol>
          <li class="radiogroup">
            <span><?php echo __('SETTINGS_USE_REWRITE'); ?></span>
            <input type="radio" name="setting[MOD_REWRITE]" value="1" id="mod_rewrite_on"<?php Request::formStatePost('setting[MOD_REWRITE]', 'radio', 1, MOD_REWRITE); ?> />
            <label for="mod_rewrite_on"><?php echo __('YES'); ?></label>
            <input type="radio" name="setting[MOD_REWRITE]" value="0" id="mod_rewrite_off"<?php Request::formStatePost('setting[MOD_REWRITE]', 'radio', 0, MOD_REWRITE); ?> />
            <label for="mod_rewrite_off"><?php echo __('NO'); ?></label>
          </li>
          <li class="radiogroup">
            <span><?php echo __('SETTINGS_SITE_UP'); ?></span>
            <input type="radio" name="setting[SITE_UP]" value="1" id="site_up_on"<?php Request::formStatePost('setting[SITE_UP]', 'radio', 1, SITE_UP); ?> />
            <label for="site_up_on"><?php echo __('YES'); ?></label>
            <input type="radio" name="setting[SITE_UP]" value="0" id="site_up_off"<?php Request::formStatePost('setting[SITE_UP]', 'radio', 0, SITE_UP); ?> />
            <label for="site_up_off"><?php echo __('NO'); ?></label>
          </li>
          <li class="radiogroup">
            <span><?php echo __('SETTINGS_MINIFIED'); ?></span>
            <input type="radio" name="setting[MINIFIED]" value="1" id="minified_on"<?php Request::formStatePost('setting[MINIFIED]', 'radio', 1, MINIFIED); ?> />
            <label for="minified_on"><?php echo __('YES'); ?></label>
            <input type="radio" name="setting[MINIFIED]" value="0" id="minified_off"<?php Request::formStatePost('setting[MINIFIED]', 'radio', 0, MINIFIED); ?> />
            <label for="minified_off"><?php echo __('NO'); ?></label>
          </li>
          <li><label for="error_mail"><?php echo __('SETTINGS_WEBMASTER_MAIL'); ?></label> <input type="text" name="setting[ERROR_MAIL]" id="error_mail"<?php Request::formStatePost('setting[ERROR_MAIL]', 'text', '', ERROR_MAIL); ?> /></li>
          <li><label for="meta_keywords"><?php echo __('SETTINGS_KEYWORDS'); ?></label> <input type="text" name="setting[META_KEYWORDS]" id="meta_keywords"<?php Request::formStatePost('setting[META_KEYWORDS]', 'text', '', META_KEYWORDS); ?> /></li>
          <li><label for="meta_description"><?php echo __('SETTINGS_DESCRIPTION'); ?></label> <input type="text" name="setting[META_DESCRIPTION]" id="meta_description"<?php Request::formStatePost('setting[META_DESCRIPTION]', 'text', '', META_DESCRIPTION); ?> /></li>
          <li><button type="submit" name="save_settings" value="yes"><?php echo __('SETTINGS_SAVE'); ?></button></li>
        </ol>
      </fieldset>
    </form>
