    <h1><?php echo __('USER_PERM_HEADER', htmlspecialchars($user->username)); ?></h1>

    <form action="<?php echo urlModr($route, $params); ?>" method="post" class="ajax-form">
      <table>
        <tr>
          <th><?php echo __('USER_PERM_PAGE'); ?></th>
          <th><?php echo __('USER_PERM_ADD'); ?></th>
          <th><?php echo __('USER_PERM_EDIT'); ?></th>
          <th><?php echo __('USER_PERM_DELETE'); ?></th>
        </tr>
<?php foreach ($pages as $page):
  if ($page->permission == null)
    $page->permission = 0;
?>
        <tr>
          <td class="<?php echo ($page->parent ? 'subpage' : 'page'); ?>"><?php echo htmlspecialchars($page->title); ?></td>
          <td><?php if (!$page->parent): ?><input type="checkbox" name="permissions[<?php echo $page->id; ?>][]" value="1"<?php echo ($page->permission & PERMISSION_ADD ? ' checked="checked"' : ''); ?> /><?php endif; ?></td>
          <td><input type="checkbox" name="permissions[<?php echo $page->id; ?>][]" value="2"<?php echo ($page->permission & PERMISSION_EDIT ? ' checked="checked"' : ''); ?> /></td>
          <td><input type="checkbox" name="permissions[<?php echo $page->id; ?>][]" value="4"<?php echo ($page->permission & PERMISSION_DELETE ? ' checked="checked"' : ''); ?> /></td>
        </tr>
<?php endforeach; ?>
      </table>

      <table>
        <tr>
          <th><?php echo __('USER_PERM_MODULE'); ?></th>
          <th><?php echo __('USER_PERM_ALLOW'); ?></th>
        </tr>
<?php foreach ($controllers as $controller):
   if ($controller->configurable): ?>
        <tr>
          <td><?php echo htmlspecialchars($controller->name); ?></td>
          <td><input type="checkbox" name="controller_permissions[<?php echo $controller->id; ?>]" value="1"<?php echo ($controller->user ? ' checked="checked"' : ''); ?> /></td>
        </tr>
<?php endif;
endforeach; ?>
      </table>

      <p><button type="submit" name="save_user_permissions" value="yes"><?php echo __('SAVE'); ?></button></p>
    </form>
