<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="sv" xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>KWE</title>
  <meta name="keywords" content="<?php echo htmlspecialchars(META_KEYWORDS); ?>" />
  <meta name="description" content="<?php echo htmlspecialchars(META_DESCRIPTION); ?>" />
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link type="text/css" title="KWE" href="<?php echo FULLPATH; ?>/css/kwe.css" rel="stylesheet" media="screen" />
  <link type="text/css" href="<?php echo FULLPATH; ?>/css/kwe_print.css" rel="stylesheet" media="print" />
  <!--<link type="image/vnd.microsoft.icon" href="<?php echo FULLPATH; ?>/favicon.ico" rel="icon" />-->
</head>

<body>

<div id="header"></div>

<div id="page">

  <div id="content">
    <h1>Vi uppgraderar!</h1>
    <h2>...och är snart tillbaka</h2>

    <p>Just nu förändrar vi vår webbsida, därför måste vi stänga ner den ett tag.</p>
  </div>

  <div id="footer">
    <p>Copyright &copy; <a href="http://kekos.se/">Christoffer Lindahl</a>, 2009-2012</p>
  </div>

</div>

</html>